# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"myfunc": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ivotron.github.io/mylib/"

git_url = "https://github.com/ivotron/mylib/tree/master/"

def custom_doc_links(name): return None
